/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("org.slf4j:slf4j-api:2.0.0-alpha7")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("com.google.guava:guava-testlib:31.1-jre")
    testImplementation("org.slf4j:slf4j-log4j12:2.0.0-alpha7")


}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("src.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
